_default:
  @just --choose

checks:
  #!/usr/bin/env bash
  set -x
  cargo clippy --all-targets
  cargo fmt --all -- --check

clippy-pedantic:
  cargo clippy --workspace -- -W clippy::pedantic

run-example name:
  bacon ex -- {{name}}

run-examples:
  cargo run --example simple
  cargo run --example daisy_form
  cargo run --example daisy_xtra

tmux-run-example name:
  #!/usr/bin/env bash
  tmux new-window
  tmux split-window -v -p 25
  tmux split-window -h
  tmux select-pane -t 0; tmux send-keys "just run-example {{name}}" C-m
  tmux select-pane -t 1; tmux send-keys "http" C-m
  tmux select-pane -t 2; tmux send-keys "npm run browser-sync" C-m
  tmux select-pane -t 0
